# Site settings
title: Nerds Who Run
email: hi@nerdswhorun.com
url: https://nerdswhorun.com
description: "Nerds Who Run is a Boston running group for nerds. If you're a nerd whose an avid runner or just getting into it come out with us!"
skills: "Weekly Running Group For Nerds"
meta_author: Darion Miller

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Nerds Who Run
  location: Boston Esplanade
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nerdswhorun
  - title: facebook
    url: http://facebook.com/nerdswhorun
  - title: instagram
    url: http://instagram/nerdswhorun


# Postal address (add as many lines as necessary)
address:
  - line: 

# Credits content
credits: 'Built in Boston for Boston'

# Build settings
markdown: kramdown
permalink: pretty
